#!/usr/bin/env bash
#This file print fizz buzz and fizzbuzz
for num in {1..100}
do
	if [[ $(expr $num % 3) -eq 0 ]] && [[ $(expr $num % 5) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $(expr $num % 5) -eq 0 ]]
	then
		echo "Buzz"
	elif [[ $(expr $num % 3) -eq 0 ]]

	then
		echo "FizzBuzz"
	else
		echo $num
	fi
done
