#!/usr/bin/env bash
# This script is displaying  hours and time
hr=0
min=1
while [[ $hr -lt 13 ]]
do
	min=1

	echo "Hour: "$hr

	while [[ $min -lt 60 ]]
	do
		echo $min
		((min++))

	done

	((hr++))
done
