#!/usr/bin/env bash
#Checks for the existence of a file called school
school="school"
if [[ -e ${school} ]]
then
	echo "school file exists"
	if [[ ! -s ${school} ]]
	then
		echo "school file is empty"
	elif [[ -s ${school} ]]
	then
		echo "school file is not empty"
	fi
	if [[ -f ${school} ]]
	then
		echo "school is a regular file"

	fi
elif [[ ! -e ${school} ]]
then
	echo "school file does not exist"
fi
