#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sudo bash -c 'echo "8.8.8.8         facebook.com" >> /etc/hosts.new'
sudo cp -f ~/hosts.new /etc/hosts
