#!/usr/bin/env bash
sudo cp /etc/hosts /etc/hosts.old
sed -i 's/^127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts.old
echo "8.8.8.8		facebook.com" | sudo tee -a /etc/hosts.old
sudo cp -f /etc/hosts.old /etc/hosts
